I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/test_as_ref.rpy", line 107, in script call
    call sub_scene_index_2_sub_screen
  File "game/screens/test_as_ref.rpy", line 107, in script call
    call sub_scene_index_2_sub_screen
ScriptError: could not find label 'sub_scene_index_2_sub_screen'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/test_as_ref.rpy", line 107, in script call
    call sub_scene_index_2_sub_screen
  File "/home/account/Python/renpy-6.99.14.3-sdk/renpy/ast.py", line 1384, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/screens/test_as_ref.rpy", line 107, in script call
    call sub_scene_index_2_sub_screen
  File "/home/account/Python/renpy-6.99.14.3-sdk/renpy/script.py", line 873, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'sub_scene_index_2_sub_screen'.

Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
abstract 1.0
Mon Apr 23 13:10:05 2018
