I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/test_screen/test_as_ref.rpy", line 4, in script
    if pc.fromCH:
  File "game/screens/test_screen/test_as_ref.rpy", line 4, in <module>
    if pc.fromCH:
AttributeError: 'Player' object has no attribute 'fromCH'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/test_screen/test_as_ref.rpy", line 4, in script
    if pc.fromCH:
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1729, in execute
    if renpy.python.py_eval(condition):
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/python.py", line 1919, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/python.py", line 1912, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens/test_screen/test_as_ref.rpy", line 4, in <module>
    if pc.fromCH:
AttributeError: 'Player' object has no attribute 'fromCH'

Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
abstract 1.0
Mon Apr 23 18:22:46 2018
