I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/exampl_map.rpy", line 15, in script
    call screen planets #Displaying the imagemap
  File "renpy/common/000statements.rpy", line 519, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Screen planets is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/exampl_map.rpy", line 15, in script
    call screen planets #Displaying the imagemap
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1828, in execute
    self.call("execute")
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1816, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/statements.py", line 177, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 519, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/exports.py", line 2659, in call_screen
    show_screen(_screen_name, _transient=True, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/screen.py", line 1060, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen planets is not known.


Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
abstract 1.0
Tue Apr 17 08:02:01 2018
